name: Docker Image CI

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'The branch to build'
        required: true

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
  
      - name: Build and deploy Container App
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: ${{ github.workspace }}/src
          acrName: ddvgpt
          containerAppName: ddvgpt.azurecr.io
          resourceGroup: DDV-AI
      
